In [3]:
import numpy as np

In [23]:
#The Basics
a = np.array([1,3,6], dtype='int32')
print(a)

[1 3 6]


In [25]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [27]:
#Get Dimensions
a.ndim

1

In [29]:
#Get shape
b.shape

(2, 3)

In [31]:
#Get Type
a.dtype

dtype('int32')

In [33]:
#Get size
a.itemsize

4

In [42]:
#Get total size
a.nbytes

12