In [1]:
import numpy as np

In [3]:
#Accessing/changing specific elements

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#Get a specific element [r, c], python index starts at 0
a[1, 5]

13

In [21]:
#get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
#Get specific column
a[:, 0]

array([1, 8])

In [33]:
#Getting a lil more fancy [startingindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [35]:
a[1,5]= 20
print(a)

a[:,2]= [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [41]:
#3-d example
b = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
#[Dimension, row, column]
b[0,1,1]

4

In [55]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b[:,1,:])
print(b)

[[9 9]
 [8 8]]
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
