In [4]:
import numpy as np

In [23]:
# 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
#1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [31]:
np.full((2,2),4,dtype='float32')

array([[4., 4.],
       [4., 4.]], dtype=float32)

you can use np.full_like so you can turn an specific number or all the numbers on an already created array to be that number

In [42]:
#random decimanl numbers
np.random.rand(4,2)
#if you wanna pass a shape you can do np.random_sample(a.shape)

array([[0.74697091, 0.20565413],
       [0.84702852, 0.13606798],
       [0.85623705, 0.26686033],
       [0.74976339, 0.23178793]])

In [52]:
#random integer values (from, to, size)
np.random.randint(-4,8, size=(3,3))

array([[ 5,  3,  2],
       [-3, -4, -4],
       [ 4,  7,  1]])

In [82]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
ar = np.array([[1,2,3]])
r1 = np.repeat(ar,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [108]:
my_arr = np.zeros((5,5))
my_arr[0,:]=[1,1,1,1,1]
my_arr[4,:]=[1,1,1,1,1]
my_arr[:,0]=[1,1,1,1,1]
my_arr[:,4]=[1,1,1,1,1]
my_arr[2,2]=9
print(my_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###
Mathematics

In [53]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [47]:
a+2
print(a)

[3 4 5 6]


In [11]:
a-2

array([-1,  0,  1,  2])

In [13]:
a*2

array([2, 4, 6, 8])

In [15]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [57]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [55]:
a ** 2

array([ 1,  4,  9, 16])

In [61]:
#take the sin of all values and the cos
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


Linear Algebra

In [13]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [17]:
#deteminant
c = np.identity(3)
np.linalg.det(c)

1.0

In [19]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [23]:
np.min(stats, axis=1)

array([1, 4])

In [31]:
np.max(stats, axis=1)

array([3, 6])

In [45]:
np.sum(stats, axis=0)

array([5, 7, 9])

Reorganizing Arrays

In [18]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2)) 
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
#horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Micellaneous

In [60]:
filedata = np.genfromtxt('data.txt', delimiter=',')
#filedata.astype('int3')2
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

Boolean Masking and Advanced Indexing

In [69]:
print(filedata > 50)
filedata[filedata > 50]

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [71]:
#you can index with a list and numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [79]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [85]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])